# Example: create a .env file (do NOT commit) with:
#   AZURE_OPENAI_API_KEY="..."
#   AZURE_OPENAI_ENDPOINT="https://your-endpoint.openai.azure.com/"
#   AZURE_OPENAI_DEPLOYMENT="gpt-4.1"
#   AZURE_OPENAI_MODEL="gpt-4.1"
#   AZURE_OPENAI_API_VERSION="2024-06-01"
#   AZURE_OPENAI_TEMPERATURE="0.0"
#   AZURE_OPENAI_TOP_P="1.0"
#   AZURE_OPENAI_SEED="1"
#

